# Generated by Django 5.1 on 2024-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('maiden_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=50)),
            ],
        ),
    ]
